### ISSUE TITLE
axios instance 추가 

### ISSUE THREAD

**Issue by hangooksaram** [Da-ily/Da-ily#108]
### 🌱 기능 설명

* custom config 를 가진 axios instance 추가

### ✅ 할 일

* axios 라이브러리 설치
* custom config 설정

**Comment by puranium235** [comment]
그냥 `fetch`말고 `axios` 라이브러리 사용하시나요?

**Comment by hangooksaram** [comment]
> 그냥 `fetch`말고 `axios` 라이브러리 사용하시나요?

앗 관성적으로 쓴거라서 딱히 이유는 없어서 이 부분도 논의해볼까요?

**Comment by puranium235** [comment]
`axios`에서 특별히 사용하는 기능이 없으면 `fetch`로 하려고 했었는데 그냥 관성적으로 `axios`로 씁시다ㅎㅎㅎ 많이들 쓰는거같으니까요

**Comment by hangooksaram** [comment]
넵 그렇다면 `axios` 사용하는 걸로 하겠습니다
