### ISSUE TITLE
기능 명세 정리

### ISSUE THREAD

**Issue by puranium235** [Da-ily/Da-ily#11]
## 필수 기능
- 유저 계정 관련
  - 회원가입 (ID, 비밀번호 형식, 어떤 정보 받을지 정해야함)
  - 소셜로그인 회원가입
  - 로그인/로그아웃 (JWT 토큰 사용?)
  - 아이디/비밀번호 찾기
  - 닉네임 변경 (중복 허용?)
  - 비밀번호 변경 (마이페이지)
  - 회원탈퇴
  - 회원, 게시물 관리용 관리자 권한 계정
- 기본 다이어리
  - 페이지 양식 선택
  - 페이지에 텍스트 입력
  - 페이지에 그림을 그리기
  - 페이지에 스티커 추가
  - 위의 꾸미기 항목들을 수정, 이동
  - 다이어리를 pdf 또는 이미지로 저장
- 커뮤니티 기능
  - 꾸민 다이어리 페이지를 커뮤니티에 공개
  - 공개한 페이지를 비공개로 전환
  - 공개된 다이어리에 좋아요 누를 수 있다
  - 인기 다이어리 상위 노출

## 추가 기능
- 다이어리 관련
  - 사진을 추가할 수 있다
  - 사진을 편집할 수 있다
  - 날짜와 페이지를 연동
  - 오늘의 키워드를 추천해준다
  - 다이어리를 여러 권으로 확장한다
  - 페이지에 노래를 추가할 수 있다
  - 년도별, 월별 모아보기 기능
  - 북마크
- 커뮤니티 관련
  - 유저를 검색할 수 있다
  - 원하는 유저의 공개 다이어리 목록을 볼 수 있다 (기본적으로는 유저마다 보는게 아니라 공개된 전체 리스트로만 보이게 하는걸로 생각했습니다)
- 기타
  - 타임캡슐 기능
  - 비회원의 사이트 사용 고려

## 프론트 한정 추가 기능
- 폰트를 바꿀 수 있다
- 펜의 색, 두께, 질감을 바꿀 수 있다
- 마스킹테이프를 추가한다
- 떡메를 추가한다
- 스탬프를 추가한다
- 책 표지를 다양한 종류로 만든다
- 다이어리 넘기는 효과를 추가한다
- 다이어리의 두께, 형태 등 디테일을 추가한다
- 홈페이지 테마를 다양하게

### ✅ 할 일

추가, 삭제, 핵심<->추가 간 이동, 디테일 추가 등 의견 주세요

**Comment by gomudayya** [comment]
너무 좋아요!!

분류는 잘 되어있는 것 같고

[ 회원 가입 입력 정보]
- 이메일(비밀번호 찾기 용도), 닉네임 정도면 괜찮을 것 같아요

[ 커뮤니티 ]
- 저는 트위터나 페이스북의 피드처럼 무한 스크롤 방식도 생각해봤는데, 다른 분들 의견도 궁금하네요

**Comment by SSUHYUNKIM** [comment]
구체적으로 깔끔하게 정리해주신 것 같아요!!

[닉네임 변경]
커뮤니티에서 유저를 검색할 수 있는 기능이 있기 때문에 저도 닉네임은 중복을 허용하지 않는 게 좋을 것 같아요.

[커뮤니티]
공개한 다이어리에 좋아요가 눌리면 알림으로 알려주는 것도 있으면 좋을 것 같아요. 알람 확인하고 좋아요 한 사람 다이어리를 반대로 구경하러 가는 그런 게 있으면 좋겠어요.

[건우님 의견]
인기 다이어리가 상위 노출되는 구조인데 무한 스크롤을 쓰면 너무 특정 다이어리만 계속 보일 것 같아서 무한 스크롤 사용 시 
1. 최신순 / 인기순 정렬 기능 사용
2. 오늘의 Top3 등 일부 인기 다이어리만 상위 노출
이런 식으로 조금 확실하게 정하고 하는게 좋을 것 같아요.

**Comment by kwoncha** [comment]
너무 좋아요!!

[유저 계정 관리]
  -  닉네임 변경 (중복 허용?) 에서 만약 허용한다면 고유 id를 닉네임 옆에 #태그로 넣으면 자신이 원하는 닉네임을 사용할 수 있고 
     재밋을 것 같아요
  - ex) 롤이라는 게임에서도 중복 닉네임을 허용해주더라고요 - 깃허브(닉네임)#kwoncha(고유 아이디)

**Comment by puranium235** [comment]
[회원가입 정보]
이메일, 닉네임, 비밀번호만 설정하면 로그인할 때 이메일을 아이디로 쓰는건가요? 아니면 여기에 id를 더해서?
이메일 인증을 받나요? 인증을 받는다면 번거롭고 안받는다면 계정을 까먹었을때 영영 잃어버릴 수도 있습니다. 선택으로 두는 것이 좋을까요?
아이디 찾기나 비밀번호 찾기는 어떻게 그 유저인지 검증할까요? 위에 이메일에 대한거에 더해 확인 질문이나 이름같은걸로 찾을 수 있게 해야할까요?

[닉네임]
중복허용x 또는 고유id부여 - 고유id 넣는 경우에 계속 바꿀 수 있는 식으로 생각하시나요? 롤이나 디스코드나 유저가 원하는대로 고유id를 제한 없이 바꿀 수 있는걸로 알고있습니다.

[커뮤니티]
무한 스크롤 or 페이지 넘기기 중 무한 스크롤을 선택. 
정렬 기능이나 인기순 정렬에 제한을 두기
좋아요 알림과 누른 유저 보여주기 - 좋아요를 익명으로 생각했었는데 기명으로 보여줘도 될 것 같아요. 이러면 알림을 모아서 보여주는 탭이 따로 필요하겠네요.

**Comment by gomudayya** [comment]
[ 회원 가입 ]

저는 회원 가입 과정을 최대한 간소화 하는 것이 좋다는 입장이라 
입력 정보를 아래와 같이 가져가는 것이 좋을 것 같습니다.

- 아이디     (필수)
- 비밀번호 (필수)
- 닉네임     (필수)
- 이메일     (선택 , 단 기입하지 않으면 아이디, 비밀번호 찾기 기능을 이용할 수 없다고 표기. 추후에 설정 가능)

Q. 이메일을 아이디로 같이 사용하는 것이 좋은가?

-> 저는 이메일을 아이디로 사용하는 것은 로그인할 때 ID가 너무 길어서 불편할 것 같습니다.

가입 시에 이메일 인증을 받는 것이 여러 부작용을 완전히 차단할 수 있을 것 같긴 하지만
당장 저부터 회원 가입 할 때 이메일 인증 요구하면 웹 사이트 꺼버리는 사람이라서요.....

[ 닉네임 ] 

고유 id 사용한다면 

- 회원 가입할 때 임의의 고유id를 사이트에서 임의로 부여할지? 아니면 사용자가 기입할지? 
  (전자는 트위터고, 후자는 디스코드 같네요)

도 생각해보아야 할 것 같습니다

**Comment by puranium235** [comment]
[회원 가입]
저는 수현님 의견대로
- 아이디 (필수)
- 비밀번호 (필수)
- 닉네임 (필수)
- 이메일 (선택 , 단 기입하지 않으면 아이디, 비밀번호 찾기 기능을 이용할 수 없다고 표기. 추후에 설정 가능)
정보를 받고, 이메일 설정시 인증하게 하는건 어떨까 싶습니다.

[닉네임]
고유id는 닉네임 중복방지용으로 생각되는데 개발이 용이하게 하려면
- 중복 닉네임 금지, 고유id 없음
- 닉네임 자유, 고유id 사이트에서 부여
둘 중 하나가 좋지 않을까요?

**Comment by puranium235** [comment]
비회원 기능을 추가기능으로 넣었는데 꾸미기 체험정도는 열어줘야 저희 사이트 진입장벽이 조금 낮아지지 않을까 싶어요

무슨 사이트인지 잘 모르는데 가입부터 하라고 하면 거부감이 들더라고요

홈에서 바로 꾸미기를 체험할 수 있게 하는 대신 기능을 제한하고 가입해야 전체 다 쓸 수 있게 하고, 로그인한 유저의 홈은 본인의 다이어리 모음 등으로 홈 화면이 바뀌게 하면 어떨까요?

**Comment by kwoncha** [comment]
[비회원 기능]
저는 좋다고 생각해요. 어느 정도 맛보기 기능을 사용할 수 있다면 체험을 해보고 가입을 할 수 있으면 사용자 입장에서는 편할 것 같아요.

[닉네임]
제가 생각하는 고유 id는 로그인 id를 생각하고 있습니다 로그인 id는 중복을 할 수 없기 때문에 이게 제일 간단 할 것 같아요. 
다른 사람인지 확인 할 수 있어야 하는데 사이트 고유id는 다른 사람들이 알아보기 어려울 것 같아요!

**Comment by puranium235** [comment]
[로그인]
어떤 팀에서는 보안 문제로 소셜 로그인으로만 사용할 수 있게 했더라고요. 보통 사람들이 아이디, 비밀번호를 여러 사이트에 돌려쓰기때문에 유출되면 큰 일이 될 수 있다는 이유로요. 이런건 어떻게 생각하세요?

그리고 소셜 로그인은 어디어디 사용할까요? 구글, 카카오 하면 충분할 것 같기도 하고 네이버도 해야할까요?

[아이디와 닉네임]
소셜로그인 유저는 아이디가 없을 거라서 그걸 고유id로 사용하려면 임의로 부여하거나 유저가 추가해야 할텐데 이런거 생각하면 그냥 닉네임 중복을 허용하지 않는게 좋은거같기도 해요...

닉네임 짓기 귀찮으니까 디폴트 닉네임 넣어주는것도 좋을거같아요
"다일리1373826" 회원님 이런식으로

**Comment by puranium235** [comment]
[닉네임]
저도 누군가의 id로 비정상적인 접근을 할 가능성이 있어서 id를 공개하는건 좋지 않다고 생각해요.
더이상 논의할 점이 없으면 이대로 정리하도록 하겠습니다!

**Comment by puranium235** [comment]
기능 명세 wiki에 작성했습니다. 모두 참여해주셔서 감사합니다!  
사이트 디자인을 어떤 느낌으로 하면 좋을지 원하는 느낌의 사이트 또는 사진, 와이어프레임 등 생각나시는 만큼만 부탁드리겠습니다!
