### ISSUE TITLE
백엔드 초기 프로젝트 설정 및 CI/CD 배포 구축관련 논의

### ISSUE THREAD

**Issue by gomudayya** [Da-ily/Da-ily#14]
### 👏 회의 안건

- 스프링, JAVA 버전 결정하기
- 초기 의존성 결정하기
- 배포 및 CI/CD 구축 논의

### ✅ 할 일

- [x] 자바, 스프링 버전 결정
- [x] 초기 의존성 결정
- [x] 배포 플랫폼 결정
- [x] CI/CD 플랫폼 결정

**Comment by SSUHYUNKIM** [comment]
지금 확인했는데 해당 부분은 따로 날을 잡고 회의하는걸로 알면 될까요?

**Comment by gomudayya** [comment]
넵 제가 오늘 좀 할 일이 많아서 혹시 목요일(11-30)에 시간 괜찮으신가요?

**Comment by SSUHYUNKIM** [comment]
오후 11시 30분 말씀하시는걸까요?

**Comment by gomudayya** [comment]
아뇨 아뇨 날짜를 말한거였습니다

**Comment by kwoncha** [comment]
목요일은 저녁 8시 이후에 가능합니다!

**Comment by SSUHYUNKIM** [comment]
앗 모리님 이거 백엔드 회의라서 참석 안하셔두 괜찮아요!

**Comment by gomudayya** [comment]
그러면 목요일 3시에 디스코드에서 회의 하기로 해요 !!

**Comment by SSUHYUNKIM** [comment]
넵!
