### ISSUE TITLE
공통 컴포넌트 작성

### ISSUE THREAD

**Issue by puranium235** [Da-ily/Da-ily#35]
### 🌱 기능 설명

여러 페이지에서 공통적으로 사용하는 컴포넌트를 작성합니다. 컴포넌트에서 디자인, 안의 텍스트, 클릭시 행동 등만 바뀌고 기본적인 동작이 동일하다면 공통 컴포넌트로 만들어서 재활용 합니다.

### ✅ 할 일

지난번에 상의한 내용. 추가/삭제/변경 등 말씀해주세요.

- [ ] 로그인, 회원가입 버튼
- [ ] (비회원 다일리, 커뮤니티의) 로그인 버튼
- [ ] 다일리, 관리자 페이지의 왼쪽 메뉴목록
- [ ] 큰 로고
- [ ] 작은 로고
- [ ] 아이디
- [ ] 기존 다이어리 버튼(admin, 태그에도 사용)

### 🥨 기타

각자 만들 컴포넌트 아래에 달아주세요!

**Comment by puranium235** [comment]
공통 색상 파일로 만들고 input, button 만들겠습니다.

**Comment by kwoncha** [comment]
아이디, 기존 다이어리 버튼, 큰 로고, 작은 로고 한번 만들어 보겠습니다!

**Comment by puranium235** [comment]
새 이슈 파서 만드시는게 편하실거에요! 둘이 같은 브랜치에서 작업하면 충돌날수도 있어서
