### ISSUE TITLE
공통 로고

### ISSUE THREAD

**Issue by kwoncha** [Da-ily/Da-ily#37]
### 🌱 기능 설명

test겸 로고 파일 pr

### ✅ 할 일

- [x]  큰 로고 - 피그마에 구현 완료 
- [x]  작은 로고

### 🥨 기타

로고는 이미지로 넣을지 글꼴로 넣을지 정하지 않아, 나중에 고화질로 받기 좋게 구현했습니다.

**Comment by puranium235** [comment]
로고 svg 이미지로 하셨나요?

**Comment by kwoncha** [comment]
아니요 아직 추출안했습니다!! svg로 하면 될까요??

**Comment by puranium235** [comment]
편하신대로 해주세요! 궁금해서 여쭤봤습니다ㅎㅎ 깨지지만 않으면 되죠!

**Comment by kwoncha** [comment]
색상을 일단 안정하고 블랙으로 했는데 혹시 다른색상으로 변경해서 할까요?!?

**Comment by puranium235** [comment]
예쁘다고 생각하시는 색으로 해주세요~
