### ISSUE TITLE
12/19 정기회의

### ISSUE THREAD

**Issue by puranium235** [Da-ily/Da-ily#42]
### 👏 회의 안건

12/19 20:00 정기회의에서 이야기할 내용을 추가해주세요

### ✅ 할 일

- [x] 지난 주 목표와 진행상황 공유
- [x] 이번 주 목표

### 🥨 기타

FE-BE간 더 논의하고싶은 내용이 있다면 추가해주세요

**Comment by gomudayya** [comment]
API 명세서 검토 및 피드백

**Comment by gomudayya** [comment]
- 꾸민 다이어리를 DB에 어떠한 형식으로 저장을 해야 할까?
- 혹은 DB에서 어떤 형태로 가져와야 프론트엔드에서 렌더링 하기 수월할까? 

 -> 계속 고민 해야 할 문제 같습니다
